#!/usr/bin/env python3
"""Render the gpt-academic Python config from scoped environment variables."""

import argparse
import json
import os
import tempfile
from pathlib import Path


def _required(name):
    value = os.environ.get(name, "").strip()
    if not value:
        raise ValueError("missing required environment variable: %s" % name)
    return value


def _json_value(name, expected_type):
    value = json.loads(_required(name))
    if not isinstance(value, expected_type):
        raise ValueError("%s must contain JSON %s" % (name, expected_type.__name__))
    return value


def render_config():
    model = _required("GPT_ACADEMIC_LLM_MODEL")
    available = _json_value("GPT_ACADEMIC_AVAIL_LLM_MODELS_JSON", list)
    redirects = _json_value("GPT_ACADEMIC_API_URL_REDIRECT_JSON", dict)
    values = {
        "WEB_PORT": int(os.environ.get("GPT_ACADEMIC_WEB_PORT", "12345")),
        "LLM_MODEL": model,
        "AVAIL_LLM_MODELS": available,
        "API_KEY": _required("GPT_ACADEMIC_API_KEY"),
        "API_URL_REDIRECT": redirects,
        "DOC2X_API_KEY": os.environ.get("DOC2X_API_KEY", ""),
    }
    return "".join(
        [
            "# Generated by workspace-ctl. Do not edit or commit.\n",
            "WEB_PORT=%d\n" % values["WEB_PORT"],
            "LLM_MODEL=%s\n" % json.dumps(values["LLM_MODEL"], ensure_ascii=False),
            "AVAIL_LLM_MODELS=%s\n"
            % json.dumps(values["AVAIL_LLM_MODELS"], ensure_ascii=False),
            "API_KEY=%s\n" % json.dumps(values["API_KEY"], ensure_ascii=False),
            "API_URL_REDIRECT=%s\n"
            % json.dumps(values["API_URL_REDIRECT"], ensure_ascii=False),
            "DOC2X_API_KEY=%s\n"
            % json.dumps(values["DOC2X_API_KEY"], ensure_ascii=False),
        ]
    )


def _apply_metadata(path):
    os.chmod(path, 0o600)
    owner = os.environ.get("GPT_ACADEMIC_CONFIG_OWNER", "").strip()
    if not owner:
        return
    try:
        uid_text, gid_text = owner.split(":", 1)
        os.chown(path, int(uid_text), int(gid_text))
    except (OSError, TypeError, ValueError) as exc:
        raise ValueError(
            "GPT_ACADEMIC_CONFIG_OWNER must be a writable numeric UID:GID"
        ) from exc


def write_config(output):
    output = Path(output).expanduser()
    output.parent.mkdir(parents=True, exist_ok=True)
    content = render_config()
    if output.exists() and output.read_text(encoding="utf-8") == content:
        _apply_metadata(output)
        return output
    fd, temporary = tempfile.mkstemp(prefix=".config_private.", dir=str(output.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        _apply_metadata(temporary)
        os.replace(temporary, output)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return output


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    output = write_config(args.output)
    print("gpt-academic config ready: %s" % output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
